invite_code: abcdefg # код из инвайта
server_id: 1234567890 # id сервера
accept_server_rules: false # принимать правила сервера? (true если на сервере есть правила)
verification_reaction: https://discord.com/api/v9/channels/blabla # ссылка на первую реакцию (к примеру верификация)
giveaway_reaction: https://discord.com/api/v9/channels/blabla # ссылка на вторую реакцию (к примеру участие в розыгрыше)